---
name: test
on:
  workflow_dispatch:
  push:
    branches: ['main']


jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ghcr.io/${{ github.repository }}/${{ env.BUILD_CONTEXT }}
          tags: |
            # Track main branch with :main
            type=raw,value=latest,enable={{is_default_branch}}
            # Track PR with :pr-XX
            type=ref,event=pr
            # Parse version from explicit <subproject>/* tag
            type=match,pattern=${{ env.BUILD_CONTEXT }}/(.*),group=1

      - name: Echo tags
        shell: echo 123
      
      # - name: Build and push Docker image
      #   uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
      #   with:
      #     context: ${{ env.BUILD_CONTEXT }}
      #     push: true
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}
      #     secrets: |
      #       GIT_AUTH_TOKEN=${{ secrets.GH_TT_METAL_RO }}
