name: Lint

on:
  push:
    branches:
      - main

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest

    steps:
      - name: Uptime
        run: uptime
      - name: Hostname
        run: hostname
      - name: kernel
        run: uname -a
      - name: mounts
        run: df -h
      - name: processes
        run: ps -ax
      - name: docker image ls
        run: docker image ls -a
      - name: docker buildx du
        run: docker buildx du
      - name: env
        run: env
      - name: ls /opt/runner
        run: ls -R /opt/runner/provisioner
      - name: ls /home/runner/runners
        run: ls -R /home/runner/runners
      - name: cat
        run: cat /home/runner/runners/2.315.0/*.sh*
