---
name: test
on:
  workflow_dispatch:
  push:
    branches: ['main']
  tags:
    - .*\.wormhole_b0


jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to GitHub Container Registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: token
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ghcr.io/asrinivasanTT/test
          tags: |
            # Track main branch with :main
            type=raw,value=latest,enable={{is_default_branch}}
            # Parse version from explicit <subproject>/* tag
            type=match,pattern=(.*\.wormhole_b0),group=1

      # - name: 123
      #   uses: actions-ecosystem/action-regex-match@v2
      #   id: regex-match
      #   with:
      #     text: ${{ steps.meta.outputs.tags }} # e.g. "Test: AB#16845 try to return PR number"
      #     regex: 'ghcr.io/asrinivasantt/test:(.*)\.(wormhole_b0|grayskull)'

      # - name: Echo version
      #   run: |
      #       echo "${{ steps.regex-match.outputs.group1 }}"

      # - name: Echo arch
      #   run: |
      #       echo "${{ steps.regex-match.outputs.group2}}"

      - name: Echo tags
        run: |
            echo "${{ steps.meta.outputs.tags }}"
      
      # - name: Build and push Docker image
      #   uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
      #   with:
      #     context: ${{ env.BUILD_CONTEXT }}
      #     push: true
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}
      #     secrets: |
      #       GIT_AUTH_TOKEN=${{ secrets.GH_TT_METAL_RO }}
