name: Lint

on:
  push:
    branches:
      - main

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest

    steps:
      - name: Uptime
        run: uptime
      - name: Hostname
        run: hostname
      - name: kernel
        run: uname
      - name: mounts
        run: df -h
