name: Lint

on:
  push:
    branches:
      - main

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest

    steps:
      - name: Uptime
        run: uptime
      - name: Hostname
        run: hostname
      - name: kernel
        run: uname -a
      - name: mounts
        run: df -h
      - name: processes
        run: ps -ax
